name: Build AMI Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to push AMI to'
        required: true
        default: 'Dev' # Default environment, change as needed

permissions:
  id-token: write # This is required for requesting the JWT


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1

      - name: Make script executable and run
        run: |
          chmod +x ./scripts/build_ami.sh
          ./scripts/build_ami.sh

