name: Build AMI Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
          - Dev
          - QA
          - Prod

permissions:
  id-token: write # This is required for requesting the JWT


jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1

      - name: Make script executable and run
        run: |
          chmod +x ./scripts/build_ami.sh
          ./scripts/build_ami.sh

